version: '3'
services:
  frontend:
    build: ./front
    image: audeldiaz/flask-vue-spa-frontend
    command: npm run serve

  backend:
    build: ./backend
    image: audeldiaz/flask-vue-spa-backend
    depends_on:
      - frontend
    command: python run.py

  proxy:
    image: nginx
    volumes:
      - ./nginx/front.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/back.conf:/etc/nginx/conf.d/backend.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    ports:
      - "80:80"
      - "5001:5001"